{{ config(
    materialized = 'incremental',
    incremental_strategy = 'delete+insert',
    pre_hook = load_US_ave_info()
) }}

WITH view AS(
SELECT
    STATE AS STATE
    ,PRCNTG_SHRT_STY_RSDNTS_REHSPTLZD_AFTR_NH_ADMSN
    ,PRCNTG_SHRT_STY_RSDNTS_OUT_PTENT_EMRGNCY_DEPT_VIST
    ,NUM_HSPTLZTNS_PER_1000_LNG_STY_RSDNT_DAYS
    ,NUM_OUT_PTENT_EMRGNCY_DEPT_VIST_PER_1000_LNG_STY_RSDNT_DAYS
    -- ,PROCESS_ID AS PROCESS_ID
    ,PROCESSING_DATE AS PROCESSING_DATE
    -- ,INSERT_DTS AS INSERT_DTS
    -- ,UPDATE_DTS AS UPDATE_DTS
FROM {{source('healthcare_raw','NH_STATE_US_AVERAGES_INFO_DIM')}}
)

SELECT 
	ROUND(AVG(PRCNTG_SHRT_STY_RSDNTS_REHSPTLZD_AFTR_NH_ADMSN),2) AS PRCNTG_SHRT_STY_RSDNTS_REHSPTLZD_AFTR_NH_ADMSN
	,ROUND(AVG(PRCNTG_SHRT_STY_RSDNTS_OUT_PTENT_EMRGNCY_DEPT_VIST),2) AS PRCNTG_SHRT_STY_RSDNTS_OUT_PTENT_EMRGNCY_DEPT_VIST
	,ROUND(AVG(NUM_HSPTLZTNS_PER_1000_LNG_STY_RSDNT_DAYS),2) AS NUM_HSPTLZTNS_PER_1000_LNG_STY_RSDNT_DAYS
	,ROUND(AVG(NUM_OUT_PTENT_EMRGNCY_DEPT_VIST_PER_1000_LNG_STY_RSDNT_DAYS),2) AS NUM_OUT_PTENT_EMRGNCY_DEPT_VIST_PER_1000_LNG_STY_RSDNT_DAYS
FROM view
WHERE STATE NOT IN ('NATION')